# Generated by Django 5.1.15 on 2026-09-07 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0004_unidadmedica_contacto'),
        ('programacion', '0007_alter_programacionvisita_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('video', 'Video')], max_length=10)),
                ('ruta_almacen', models.CharField(max_length=500)),
                ('nombre_original', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_picking_packing', to='catalogos.entidad')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_picking_packing', to='programacion.jornada')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_picking_packing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evidencia de picking & packing',
                'verbose_name_plural': 'evidencias de picking & packing',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
