# Generated by Django 5.1.15 on 2026-09-14 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0003_evidenciaarchivo_usa_almacen_r2'),
        ('programacion', '0007_alter_programacionvisita_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentacionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('listo', 'Listo'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('total_fotos', models.PositiveIntegerField(default=0)),
                ('fotos_procesadas', models.PositiveIntegerField(default=0)),
                ('archivo_key', models.CharField(blank=True, max_length=500)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('error_mensaje', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentacion_jobs', to=settings.AUTH_USER_MODEL)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentacion_jobs', to='programacion.jornada')),
            ],
            options={
                'verbose_name': 'job de presentación',
                'verbose_name_plural': 'jobs de presentación',
                'ordering': ['-creado_en'],
            },
        ),
    ]
