# Generated by Django 5.1.15 on 2026-09-15 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0004_presentacionjob'),
        ('programacion', '0007_alter_programacionvisita_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evidencia', models.CharField(choices=[('foto', 'Foto'), ('video', 'Video'), ('pdf', 'PDF'), ('documento', 'Documento')], max_length=20)),
                ('nombre_archivo_original', models.CharField(max_length=255)),
                ('comentario', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('corregido_en', models.DateTimeField(blank=True, null=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('corregido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_corregidas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('evidencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='entregas.evidenciaarchivo')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_resueltas', to=settings.AUTH_USER_MODEL)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_evidencia', to='programacion.programacionvisita')),
            ],
            options={
                'verbose_name': 'notificación de evidencia',
                'verbose_name_plural': 'notificaciones de evidencia',
                'ordering': ['-creado_en'],
            },
        ),
    ]
