# Generated by Django 5.1.15 on 2026-09-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('super_admin', 'Super administrador'), ('admin_nacional', 'Administrador nacional'), ('usuario_entidad', 'Usuario de entidad'), ('visor', 'Visor')], max_length=20),
        ),
    ]
