# Generated by Django 5.1.15 on 2026-09-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('super_admin', 'Administrador'), ('admin_nacional', 'Nacional'), ('usuario_entidad', 'Capturista'), ('visor', 'Visor')], max_length=20),
        ),
    ]
